<?php require APPROOT . '/views/layouts/frontend/header.php'; ?>

<div class="checkout-container">
    <h1>Checkout</h1>
    <p>You are about to purchase the following course:</p>

    <div class="course-summary">
        <h2><?php echo $data['course']->title; ?></h2>
        <p class="price">Price: $<?php echo $data['course']->price; ?></p>
    </div>

    <form action="<?php echo URLROOT; ?>/payment/process/<?php echo $data['course']->id; ?>" method="post" id="payment-form">
      <div class="form-row">
        <label for="card-element">
          Credit or debit card
        </label>
        <div id="card-element" class="form-control">
          <!-- A Stripe Element will be inserted here. -->
          <p><em>(This is a simulated card input field)</em></p>
        </div>

        <!-- Used to display form errors. -->
        <div id="card-errors" role="alert"></div>
      </div>

      <!-- In a real Stripe integration, this token would be generated by Stripe.js -->
      <input type="hidden" name="stripeToken" value="dummy_token_for_simulation">

      <button class="btn-primary btn-lg btn-block">Pay $<?php echo $data['course']->price; ?></button>
    </form>
</div>

<?php require APPROOT . '/views/layouts/frontend/footer.php'; ?>